### PR TITLE
Hotfix filter issues

### PR DESCRIPTION
**Pull request by JeroenMe**

### CODE REVIEW

**Comment by JeroenMe** [comment]
@aaronmu this solves the weird filter problem + some other tiny fixes

**Comment by aaronmu** [comment]
@JeroenMe clearing filter removes the filter.

**Comment by aaronmu** [comment]
@JeroenMe it feels a lot faster!

**Comment by aaronmu** [comment]
@JeroenMe Dno if this is something that needs to be fixed in this bundle but when I add / remove filters, the configuration is not saved.

**Comment by aaronmu** [comment]
@JeroenMe selects should be chosen.

**Comment by aaronmu** [comment]
@JeroenMe pressing "apply" should close the popover.

**Comment by aaronmu** [comment]
@JeroenMe When I display x (25, 50 or 100) number of records and I apply a filter, the number of records is reset to 10.

**Comment by JeroenMe** [comment]
@aaronmu kunnen we deze pr mergen? en de opmerkingen meenemen naar nieuw aangemaakt issue? 
Vind het wa kak dat we deze bugfix niet kunnen applyen door andere openstaande issues

**Comment by aaronmu** [comment]
@JeroenMe sure.

**Pull request merged**
